# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e31f8a82f742db896206dc833f068da8cd4d805f3320f5595bff03f76f7e7c24ea8cf7cff2f9418351231d7db3019f08b96b1ea55e95abe580b53c9d85fb7f5b

test:
  secret_key_base: b6c5b141f0b0832b8c7c4980b0c2b723c089d4f5bf799f235111e54ce991f177ee2065b04ea37dd823b198c6ac78e2949c1268a0def0cff7c4652f7e39d86484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
